apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator
  namespace: telemetry
spec:
  interval: 10m0s
  targetNamespace: telemetry
  sourceRef:
    kind: GitRepository
    name: prometheus-operator
  path: '.'
  prune: true
  timeout: 1m
