apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-ai
  namespace: newsletter
spec:
  chart:
    spec:
      chart: local-ai
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: go-skynet
      version: "2.1.1"
  interval: 1m0s
  releaseName: local-ai
  targetNamespace: newsletter
  values:
    replicaCount: 1
