apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-iac
spec:
  chart:
    spec:
      chart: tf-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
      version: "0.15.1"
  interval: 1m0s
  releaseName: tofu-controller
  targetNamespace: flux-iac
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
