---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: trivy-operator-values
  namespace: trivy-system
spec:
  encryptedData:
    values.yaml: AgBTWfmm1nCtbUaK3N3mnakbpAPLitbx+GXVDOpL/kbPBDCnziMLcMHpPvU0wcGW5uoqZomo4nPsbhdshKDLX1Bpsv1T+v/2h7oYJPCzei+vUj4cPfv3ECp3U3iITWxJ5hjxoM4DrCY+BySusbmfIovZS4DNvLgbkWmY1Jpf/q1X9F6aWV9WIRosLunHQ+4uk/sxJC2i0GserJ7UHCKIII+ZOG7ozzHgDKsKkWLw/4mqpebqksftjyRd3E5lNrjWTIhfftWId60UpeiKah5lCVIQW9jP+iGj0YO2Knm+MZ+3zJiqG51OLlVnrMsviY+ZkyGXSG0lcpflIv8v2qfiiA4c2uuoK9/Bo2w2ZuFuu/fe8NCwjibca3ilW5UMl2tiqMcqagYTNXPShJA4Amrrr1neF95nEu1mVXl6i0X9TDOwno6Hj0Gc6MINuYiAKkSVo2FDkkjWag8ZQZzLp1oQG/pF0wQdps3EIvwo1Mgo3S/LZyrYtv2P/229HJQYAEXSlQHda+07H9VNVtIi2VPrr3D1H6LYBfH9+qVYus+3gIeKud8GxNJ6WRluFQo82QD01eq+XBuBMgV94EnmafMyPcIIciSICfm9qKU0zkoA5IeWXyQjnpPc5HEPb2NTYkiw3k12IPJfPWI8gugJvNRBWPftR4RjI8Q+nx4Jc7Avz1iRdrvsAq0nLXSmINBt/Z6vcuzXvHy9MXZ46cKcCw7FtIJyKeeHM00ebGvXOwjAYowncEv7assq51QaZOM5p4jAL35IddjwtxRM/Nwy8NlNWBUFDduTTzIRF2J0xHdhftggHvEsxem8HHFwVUwGWRCzvF6E7669d1v1ro+a4ErUvuoFvVhDbeoIjix5tk+/jz+KPWA+a0UV1ybK5pNuqFJlPsDHRNlMyN8hq02o8UiWpMXie9oBotJ5h8tI+jXoKqHGPy1gd4gqJ8bxmepyVeH0oBlgy4XjBwXKtlFKuW6rym7/Cj9wlVrYhhzvqW0/eC750UMkcJ2mTVj4KrqggWX7dHsPHnSEPwuBs70D0MHuVklzExCPghA=
  template:
    metadata:
      creationTimestamp: null
      name: trivy-operator-values
      namespace: trivy-system
