version: '3.9'

services:
  portainer:
    image: docker.io/portainer/portainer-ce:2.19.4
    restart: always
    ports:
      - '8000:8000'
      - '9443:9443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerData:/data

volumes:
  portainerData:
