---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: kube-system
spec:
  encryptedData:
    address: AgB/0IiPZRj366OOFi0Piq3FcH9D2g5jq7FAcuTXicN5nE5T9dUnQI9ueoGyDpgRagh1JGxTsAFcSPAZmqZrR20ww9s+qPZflpydDuWqJZIixBtJ5YKFZWuIpD7gPIt/h3MA+nkmCRBoXtGL5UJwq/nGebbD0O3RtXV5vZATzDLAEoz7jWmVT4t4WFB0TfokrsEb6LJC7d2JVFJkK9C3NbWsfV9tDeKCx8g3bJaaEPgu0uLfYDc49Z+iyxh7xWvS9GzaIotsdn2so7+Nwj9wiiRvszuNMsLWq+aFgNZaSlxoYZ2+lKoUrtc2VMfFb19nhSPZzZk6j5MFyn7LHNQPmc+tzGbmTOiotnKbxDNKIKJLF4A/WBenGmIh3VvoZImTQITK/pNJHisXUE5GOESIgBnTE5lZtMei6wWUA8rhz5eTYgd/zgdVthg4e6plSgSHbwHCLACgdhYdGOhEVUf1+WYtjmnDtlfhkmotzmNNGKraugrpRdXgue2LgLLooNw55f8+Jz5eaWRLcMuwwA+55eIVtD+MIzz6AkU0rDnyUtailzLsNZabFbYfNMJ/Y+XpCvM2TwrgBGh1TNi+ziF8FbW0O8Du+PRXM+Yi88TnyNYXNzW/44MiOLXSvsegMmUs6EuR0qWoCb0CY2zgMhOOHB3GFF0BP+AjYDJQj6RUdIZrjhGbwo2qvqhHtmPp7gCOoAKhGhz+Yf50t49WiOIf6hz247ds+r8gQJrxrYdgcCd+6QkjI2VNYrqcuE00D07wGu+l/bHukCr/85dsSRmBwWb3URvtTDExPK9DposzqtHYm11u7AzpwifVykCFGK4N1JOnuoeIQqkThmmXqfSJzcZx8Owz7AE6TZDU
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: kube-system
