---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: kube-system
spec:
  encryptedData:
    address: AgCUbtVGE9hsny6UO4Kk+FFkLpfGeAiDys7vrB0Y5q2ZXMzxjdJIraTfjz9Y0ibQFpoHDvrzjpJ+T+E9tNOmhn9LJkSzL4pCxKS8QN0rO+M0Iu6uz8/akByNDhLAKz6YOYKBMbzNJm0hSnuu7r+XRYBlP+sXHP6v8FK/h4mKDSbYCHFzWgnY2kzRe3frR0ANech+inzQXY/HFCRuD+gd2TuP31l5PvlKzLQBT9/7/B4vVwOJyfdGqVi3SYPTcxew3ABT1rCgcvinNPhqV/4+I90NS6GTq9CYw4FX0YK0PH2rSJW/u6LBh12+QloGUWI1WZvOwNJ4CiFCR7wLIoEehlBf9SqjOFiVnN5A4DGNEm52qly2Xe2GCb8GLn+5FjFKa/QpGecENiz+dSHAPQTEfIySIOT3S5yKjjVXMxnnHFg0GJGSa07wEYg/W4X/yrjCU2pWwIkvofASchu3e7h06k1LAkwkcV0LG1pa1UVhFai7Cl0phPb5SRCHDNtlLIlEpR/GumDuZYdHr723LEa+ExVsiMYrXIvm/GckpsWbAgu8KCoSYNNzFlF24alRjWCfaLsAllPPuZQn9HedIoBO9QKDzGUfqRzem4O7IfG0UomodE8vTfCATCDLgpxtrFU4vtHsK0Uj2J2Scj5DqkWT6zHcBfobLrgoI3CWDxqDh1NbUZzoJ7rKy+TjlX6EpAe1QMbrCDHvY4of2LhG8JccNnUhGR4tai/OH0Z91+Buzt54yFfVDJCnYMKQe4dbAHMmsi9lfqztBgM/v6R/KUX9pS9LDdHx5AocgkCbHUzKAgaNajN4UAE5VjwG419Sdc06EJ5nmDe4v8A5LI5IHiclB+O5b49Fx8+vcUse
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: kube-system
