---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBlB4i0CmHWeNo99pwMDJz6ah0U6KQL43Y7Sij7rpQIOxF9xCCPfTZQIvJ6l8fY3AgZ2aevfe/UqeN2VLMrYoUR6ZcOq8nZuwwIqU4XIQRLogUuCEZMyGJ/QuS1Umg4YfnQOfE04732RvJmC2RGL/d4iCPyGwiXT8jyB7RT28XGoykWnc9hE0JDeruU5ULBP7BeYwKTeelvC0sxrJZfhefaSEDCzP8eYtzrFgVIUnydxilDNxwlN+6AL/aDab4THvlFaV2It/vmaNvOJMJ8KOpZLAgLtbeanSjg6xvqYYrM+3jCqN56kvPr8Gyt/5CfwQcw/+b3hsHUwimkxnUZ2RKk3vajWN6hd5Fk+E19zWs7SmHu4VpFuvrD/VQSU5CPYOrXd+q9S/epGYlNcA5e4gTSaMnrTSx5kK487UwQESIHj1qGKtxmH6MSSQysCqGm91lbqa6inSwwfteTAAFuNoa2oP6moaQqqygw9vVd/oNZgy+rxz9jeBKl/u3/0qZDrJiYdobHlaYqGR9B7m4w/VFyzRTl5SPdbMk6wnrHvqEzrNPOHg+z7lbxYxVUYV98T2MpxuDy51H6gx25AiZVuTQHMtyFvIwptQ2TL+UG5G7ERSfawM/ieNXnqFYXFN83fptYsEvV+LEJMWFvWylPq0k210sZSxvQpwbRB62U6W9XGuNyNPCZpajc7/vVZlyWAPCmhqFkBhSTQRp2KrUzu1ONiIo5LOOJn+Pt3OTRZRBVlOs3BYdM+fz3Pjku3kRu7OPo/O0pdsyVT/uL+b7gGirlwa6tBxjLS1lxpyKjJQxcVikDKcjdMVfzCSkwWiKX6XP698YA7C9HkzY1mxtVrGrZUp+nu/yxWh3YZVO7aniXTIBweop9664sm6DeWZMyirG48KJSQpA3WCtbiILf7rU8yPZhHI7cth6mA1Lbonbwi1RtXxQ7vkEeNMWhwAldYgMRjk+DEVpuZjBo500b7ORtTv9IZ448wdWz5xD9NOEaEVB3fU9ABCBtujy80y+186wGgvcnxpjtx3Q3J4fiRl1E4Vhi5T25tQYv4SgKsZ3Ck5Wu7alrdWunCAFoyHt8SU0k45PFBUbbxYq75M1CGl5BO8l0Vcc7gZFXWc0ZluQsxrf1oMFW/8XqDBXwOseGGcs+jJuXwVacLg3OrXZ3PktqaCnfbllgXHRDljbHbEQ9HICDKmBgnYU1HhSoIDr87AhBtxC07bAAKnyRA28Upi6e1qdG22WTK9zf3y8EXx6Rj6T1TStYlqPCdJo=
  template:
    metadata:
      creationTimestamp: null
      name: kured-values
      namespace: kube-system
