apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kured-pod-monitor
  namespace: kube-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kured
  podMetricsEndpoints:
  - port: metrics
    path: '/metrics'
  namespaceSelector:
    matchNames:
    - kube-system
