apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
  namespace: prometheus-system
  labels:
    alertmanagerConfig: alertmanager-config
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'webhook'
  receivers:
    - name: 'discord'
      discord_configs:
        - url: 'https://discord.com/api/webhooks/1173670787455139840/X0AMEUgIOpp4hkFitTde1FEPP0B4QMhhQPGi1e6P6cQK2zHr4razQN2RqO9aoZshuFSO'
