# apiVersion: monitoring.coreos.com/v1
# kind: Alertmanager
# metadata:
#   name: alertmanager
#   namespace: prometheus-system
# spec:
#   replicas: 1
#   alertmanagerConfigSelector:
#     matchLabels:
#       alertmanagerConfig: alertmanager-config
