apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
  namespace: prometheus-system
  labels:
    alertmanagerConfig: alertmanager-config
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'discord'
  receivers:
    - name: 'discord'
      discordConfigs:
        - apiURL:
            name: discord-webhook
            key: URL
