apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: agent
  namespace: prometheus
  labels:
    prometheus: agnet
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      prometheus: agent
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      prometheus: agent
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      prometheus: agent
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      prometheus: agent
  remoteWrite:
  - url: "http://oci-kube.tail4d421.ts.net:30090/api/v1/write"
