apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: iot
  namespace: prometheus
  labels:
    prometheus: agent
spec:
  staticConfigs:
  - labels:
      job: tasmota
    targets:
    - 192.168.0.12:80
    - 192.168.0.52:80
    - 192.168.0.234:80
