apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: grafana
spec:
  interval: 10m0s
  targetNamespace: grafana
  sourceRef:
    kind: OCIRepository
    name: grafana
  path: ./overlays/cluster_scoped
  prune: true
  timeout: 1m
