apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pyroscope
  namespace: grafana
spec:
  chart:
    spec:
      chart: pyroscope
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "1.4.1"
  interval: 1m0s
  releaseName: pyroscope
  targetNamespace: grafana
