apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resources
  namespace: grafana
spec:
  interval: 10m0s
  targetNamespace: grafana
  sourceRef:
    kind: GitRepository
    name: resources
  path: "./kustomizations/oci-kube/grafana"
  prune: false
  timeout: 1m
