apiVersion: v1
kind: Service
metadata:
  name: lb
  namespace: woodpecker
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: woodpecker
    app.kubernetes.io/name: server
