apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  chart:
    spec:
      chart: woodpecker
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: woodpecker
      version: "1.3.0"
  interval: 1m0s
  releaseName: woodpecker
  targetNamespace: woodpecker
  values:
    server:
      env: []
      ingress:
        enabled: true
        ingressClassName: tailscale
        hosts:
        - host: woodpecker
          paths:
          - path: "/"
          backend:
            serviceName: woodpecker-server.woodpecker
            servicePort: 80
        tls:
        - hosts:
          - 'woodpecker'
      extraSecretNamesForEnvFrom:
      - "github-config"
      - "server-config"
      - "shared-config"
    agent:
      env:
        WOODPECKER_BACKEND_K8S_STORAGE_RWX: 'false'
      extraSecretNamesForEnvFrom:
      - "shared-config"
