apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  chart:
    spec:
      chart: woodpecker
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: woodpecker
      version: "1.3.0"
  interval: 1m0s
  releaseName: woodpecker
  targetNamespace: woodpecker
  valuesFrom:
  - kind: Secret
    name: woodpecker-values
