---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: kube-system
spec:
  encryptedData:
    address: AgBUUidntC3IuTGEPcWnpoOrrzUfCv0yzJm9mlnpXJT0S0AcKpNcWjhmJSzMsDPZNi97/p39SemvO9F5Qex0VjrOBH2LbT/G3XINatG9oJPDVLD7SM/ZLl+J6U321qY2cDUGi/vaHG5C81dn3/zQtIHCzxlSLp5B/jT+haDvlZyEgFZubdlSwUFyPcZJc4KRsfzL7nCsOeTlWqx/7iZfND9aYX0p71ACfYv0gZZ2VKCbshNxo9vTqV+WYOWtfRVku/5A64zg4oW6SYF6+oRUcINAQMYXlhmwx/b5VvjIhSCVVTjR5flIF4fyrmdo5e/ZLZ2IQFj4L7UVa7GurV83dxsfn3kt8uFFAUcgjuso+dyOb8xruvTLxlfxaLgrk/dgyPTXSN7h+h2vYw1NJnK4wPYcdhXuQTk/Rr7QwkPiIGktKDxDb1AfMJHVu5qqNM7PLFtAtZapeXQktcNmLDXRrZKzR9tdqxuYuCzv1d4GzWR1kVGW7q5wrk4cxlZd0BT2QTGNPzZ4RY6Vnp2Bf4wS+zEjtgyQhrpCNdNoJd42gudNZWJ4HsKHuMEi1M4Rw5zMC5y3lujgT48ugmgI06UvLZ2Md8l0dK6AZScOInFR3BE5ntjexTD9uOATrALuo48tCypMeuDjIhGEfKYCai0QYLZLyUxc3pmrALnxF++nNDxlENjilaSwpKsq1TnZkXdYp503j8Um35ZDIrWP3ZG+SHiYli1erpOavP+UtoZdHpEwkBs44lk86/b+NEShuHmlrsbN98R4aSJaMDaxryF45UjskDvt8rluxohKgL9yXsTm4g93jawXQx2q+l/Qqm6ITB4GksNjVpJPjUqEjWEMCjRAcpjEeB4uDS/X
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: kube-system
