---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: kube-system
spec:
  encryptedData:
    address: AgAVWkqRbi8s+gJQi4WTXt6ChHf8FQA3DsbUi9KVBKYlTmeVj1DBAwftfRoUaehShuHir8iidKgie9n+lvYvcbxDHOsQKK1R5soPNO5yRsTZTaNzww49KB8Js6omSE93dDSeOVfGkngDi9z9MYQpPBarg7pJbNyoUUqxMg1gajtKScxOvep7/nSlgOYTQlBEVuvXwB0KavxoCCvkpKmF2H/yqLeS0ikfmPgrepGIYuI23tCkSHascHnljeKYT2ejfou8OgyxmZazA6HiWruaW72UkXkXw+wFoe5FmUxun6+wfeUf4YSCBive5QVoJnwSmK5crcVTB1AocZJNGpE+j36WefZvLV8/n6XhbeeuJs0X+SASW49K4NYxdLD1mqXGJa6grbbvlWrP0X35deX/Fk4neGGiPM4hb03cD13g2zKc03iKL4ZD0jE9KAwb6ioFDRB2w0LE8TXHUQtrGjw0Rm+jBcQrcjUnpeEs6a0D3LC7dEX+xDyIYxWJPbnu+Kn8WLAKOFLnUC1bIFkc4NR6ZtiL7Fitj3yBnZVJqiobJFkm81XVJloWro8xCLJ+/2VuNncO/699VnEBgo4BSvnxdW/UX4kdnncCcOJhOsIWT7Si0YAlRsh8Fw7shiUATuNRLTfUinUuhI3OeQ8fu/irX/zuVwk3SF5CQQXvSQJDyxA6O71b8IKgGwjUgi7dA4Y22A+SJCbaJpIi1Jw4bDEhaak73taNROQFBJV625OrCG0HKt1hdYQ8JFhiLwfmV6m+4Pzuu3FjiKDV71jA/3Cp+Rry/xreddnawt5rgS2WnS4lA/zS3Ru6pe/z2Rx/WmtbsboXHiIyChZfdeoiCNQoN7PqF2NaWCYsuV6d
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: kube-system
