---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBGVWNoz9gN5bJidhThX4Uipp6WlFvfBbDGeggad1Lonu2fKmLyVq4tFDuvFQScPE2hIOY2ba5sjOktTYOClTfPi9P6a1XkouZsYLNIyg+VcPluQEZjqtn2W1XjfXAACj9/LScEo/sHOWMJd9/NRzTvwE49tNJoocA4DbTTbqkX+WqM2o12+z9jGdrNCjF+ic52qJuJGOsZZh7NBPVKGihtq5NLQ5Tzx4tEWCC2j6eIzTRLKAKMuOvCdxmt8ViIUXF3taWsIhR0f5yb4faYGAZ7BGuriotzLj56Ylhe0rF566R7ekwvDKTS70GU8SwmAWTEPc9oEgYl4VwxXNrn76kJJ+AQ/A1dCxi4EkniZtA7UWCp1W5bdlGvgdUTQMzoZ5i17rB+BD8jdVL15yAMmIKJOt/X2Goxf9BjUijCox6ENBsaLIKS29yXT1x5QkBnTRb+te/WZIf8lKYEcbpUSBD7H55Z9rPRcMi/nLOrnIHvkx/wMMNebeaNallNMEWycABNOLHDx/w34BPAzpbLRSvbK8eoj8BhDcdP3mK+pRgSQey++aYKKelErT4M6V6Im6UKxgshjygoQp1pkMIl3DaJM4pjaGHXi2ynCSkcvhtV7iOeHl+xCGnQAyi21IktDhn+U/OlX0I/xfTXqdX20mVU1I1WrcUZQY7+4tZeJgF8xW3ErLKsOIpRPr7OYaRlHRuTrClifSLUV3OTQuIlp/wMWyi1vIXmU+G2IO01EhkvjWyZjTNfYL76j6DG09WLTrlIg0HXjLQGBlFYg45DbyzLOgif5JCitdnKfP/rGGr7QU4KrHvHD4T6lBGOcCA5+tWsVRtQcvLRUUIJmHTiPiWhloNx1cwe0ZhNg3dEbEevdmEvD+KuFmOWc4d/09rjY7RzhHclxBJCr/NeHA7/fLZyDqG4B3FapOQqsGzqJN6MLNs/9XmRe0UOHdKnuIefnQkCUBMvJsEh0nkZOkinugaCrxYoXFPOttHDK+SaUQKjVdmIxNO7J/fck/BUTWSxQ1DRquoL+ZSEjwX28duukWIPPKoRKC2UqCdx26sjmje0nSHJCAmVXmS0H2kHq7ngu5UfBvrNFzxw5aypCh2GS5HHBcBrmGelrZwzCD4kyY3Ptaq0pqF1Qw==
  template:
    metadata:
      creationTimestamp: null
      name: kured-values
      namespace: kube-system
