---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBvztQSvrPHoBmhH4c4kogL6Ia8f/ueJAlJHm/flw6Ap5RBJY1XDYjyR434PUxzOytjVRwl9G6Q880J2du1AutJzUhbS69fBSE+lNaBmpRMMfnTY57Po+yMqS9+UCLlZ6t4jDG93n59UF1C0vKqpFlFQ5QZzXXZx33kTr+vEZXNyQFCs+w/VSnJuE/+U9mS3sGi1c0ogCf1nylOmcHmvepvb3nA1ycx0bIdCbGywgGYTxk6kf9Y2cDtnLp5Ja9jZuh0dOnOqREZPvdxQQMHBrUIf8AW301LZyy7DFw+xRCB8TzDIQnbJDW6ZuXYDfnsuT91TtvlPSk6ywaYOedWoml74Fx+XQQOzgvq6+J5vrM+chdM3dSzzRmcMfO/WQ5OVUNTG7/5ffHRSCjPklENb4AnT6AotbJo+IV844kJMivaDjcavLtJ1zydLpnaD4LUWw390no43By9XCEk9vtSIbfk23lRBKEZNeMmIvjIjbf7R2x4ymGYRelUQSjSF5hqzj3lHiXU9q8Qwnmrn7mnBGCj7fMRogMq2k8SMx0IJTe97ZGnSiCq6hEmqcIlhMUdzKm45eqRTJM63g1U73eMFsX3FOoXIzRmtkNThlXdDTssFM/fSCsTp1JguEvmTbUCOVOi+rltpmJIQV2A76cZjj3uvwMCCOCHSGPSsmdpLqmEw7dhjvLpufAbn/SZcguPFT68ZIAQQ6tMUwCnl1KyzvxS4ZjM1UXHfZh+q4FLQEv6kYzWtqxLw7himrcUrY4vQK6zjLf9CAWsXSJrJdfzN8SHqw/yHePteKBLBAD+syZuN/xn8ThHvIcusY9tLOQX86nnGIZP8aMvF4ROhjI7IyWZRmdAbiZsJOg+Gq4l77OsD2iD5ecqVFK0i7S7YWjCHcjwic4luf7e8dtMXTA/jmj30PBVtLzaVXoXLb67F9SzxkICYJ+zpM6w5gIXP84XDHOQxEpNJ46Mg1Q1y9qGDoLPhropJgdNvHB2hXyZ7MXSsEmRrb+jpN6wqGPXFilMq2H73MILByfE343l9lbqXjFHlcdABCKRpN12XkCusOzgp7xZJ76HWPE5q5FNwDwRKGxIyJutsFlISLZkFhiRVt+gTWUkrJCtEOFGwyah2JImBX+cxdMQuw==
  template:
    metadata:
      creationTimestamp: null
      name: kured-values
      namespace: kube-system
