apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/alerts.AlertmanagerConfig.yaml
- ./resources/discord-webhook.SealedSecret.yaml
- ./resources/grafana.Grafana.yaml
- ./resources/kube-prometheus-stack-grafana.SealedSecret.yaml
# dashboards
- ./resources/dashboards/pve-dashboard.GrafanaDashboard.yaml
- ./resources/dashboards/energy.GrafanaDashboard.yaml
- ./resources/dashboards/security.GrafanaDashboard.yaml
