apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/alerts.AlertmanagerConfig.yaml
- ./resources/grafana.Grafana.yaml
- ./resources/pyroscope.GrafanaDatasource.yaml
- ./resources/tempo.GrafanaDatasource.yaml
