apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: collector
  namespace: otel-system
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
        timeout: 10s

    exporters:
      otlp/tempo:
        endpoint: "tempo.grafana:4317"
        tls:
          insecure: true

      prometheus:
        endpoint: "0.0.0.0:8080"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: collector-pod-monitor
  namespace: otel-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
  podMetricsEndpoints:
  - port: prometheus
    path: '/metrics'
  - port: metrics
    path: '/metrics'
  namespaceSelector:
    matchNames:
    - otel-system
