apiVersion: v1
kind: Service
metadata:
  name: podinfo-ts
  namespace: kubecon-eu24
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: podinfo
  ports:
  - name: http
    port: 9898
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 9999
    protocol: TCP
    targetPort: grpc
