apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-np
  namespace: prometheus-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
    nodePort: 32103
