apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus-system
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "25.19.0"
  interval: 1m0s
  releaseName: prometheus
  targetNamespace: prometheus-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
