apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: "grafana"
spec:
  external:
    url: http://loki-stack-grafana.grafana:80
    adminPassword:
      name: loki-stack-grafana
      key: admin-password
    adminUser:
      name: loki-stack-grafana
      key: admin-user
