apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: parca
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: Parca
    type: parca
    access: proxy
    url: http://parca.grafana:3100
    isDefault: false
    editable: true
