apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: parca
  namespace: parca
spec:
  chart:
    spec:
      chart: parca
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: parca
      version: "4.19.0"
  interval: 1m0s
  releaseName: parca
  targetNamespace: parca
