apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager
  namespace: prometheus-system
spec:
  encryptedData:
    alertmanager.yaml: AgCtRn2sVn6VQaKHyS67EFyG8EavOtplmVFBdla7J7ltYgSkclKZU1QPjwT0LD31yCPsiP5Sr/n9S8vxhtGAObxQMnDvubakQhSW/C9ipJTF3ROnJpsZlPcqIwU/YE3CD2eEInTdAvooDAVlh90t+E47fb+peVoME9Dyukw39rVgODpNo0rfR2bkK12ufuaWnG2nwbQBHzxbNYz5l4W4d7APVbNEav11VXMILy0yjLaq8Dl7LDQ+ShmENIPX7ZvIYe3fF2N7jywEC9fyVanJWj95OHM6vjcuhD7uDNeHJcP3zh/wbSEKkMXoLL38OgXHEG15ypn4E9jAXPNLMhhO3wnDQ2ZVwEWqrOMZCvdtdsHnGW4U0q4ocPe+VSIoWVkyz9cGC6CCPYWCT/CSswhwib9bX5U5Oh653C9mzpXAHtTsWs+aF3Zb80EigA/J4uSF7xiL134rRqOEW3T6DRkC8yjCA7xy/+J0FPa49esDQGwotTcLfyXhvWxO+c07F6AhyxbLjUkQ5WcqUOR+Hmr0EDtH9D6GS3GGYnGYFW2olyx7BGfkDqCuh75JwAwbGECUHrfqrcH37z+wFwYG1KojqelbbCLitpAbB17N/B1c2hC2Q7eEFHBgN3Ejku0G4gLQmrXWpTpLcmIAO7hDbZqRE6CxTBAcM06y8S2CqpmHJRt0HBtQoXTkVu1uBy27aKQ8U2mt2i7Me13ZGrhsSGrnmzzYbVsmP6bWCDeDsCaieyLsS3klsKMP13ZLpAmnvbaJdOc564g1nO4dcz23sVmcSL1VglXyeytpwSLGGFuVyV+m7yvmtTKJ2dhOvUuOw2v/ukao2x0gT6TerHI/NbXD1TsBU5YZagPmmAl0+pX4XrF37u3eUKgtg8tTq9me5tFZ/kq9KV+43+ftl/7R/jAvoAad427wQfGEH6UwOJMVwPWGN32Zgh2SR5nI351hUtd0PtEAdsmRmQzqLjdwlstUSgHUjRIxCOn8O0Fd3SJh3rlr35SuhLuaHJsOueNEsT6BPUahCR+L5pM592dCRLFR0uaXk21MmHdpffvfZ67jF4ucKrCd2EIuNGss8w/oiA39IWH5VyuxrVJWT3TmduWcxL6pdTP+ig6W+KkESZVpIQg=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager
      namespace: prometheus-system
