apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: prometheus-system
spec:
  chart:
    spec:
      chart: prometheus-node-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "4.30.0"
  interval: 1m0s
  releaseName: node-exporter
  targetNamespace: prometheus-system
