apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resources
  namespace: prometheus-system
spec:
  interval: 10m0s
  targetNamespace: prometheus-system
  sourceRef:
    kind: GitRepository
    name: resources
  path: "./kustomizations/oci-kube/prometheus-system"
  prune: false
  timeout: 1m
