---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-o11y
spec:
  chart:
    spec:
      chart: kube-state-metrics
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "5.21.0"
  interval: 1m0s
  releaseName: kube-state-metrics
  targetNamespace: kube-o11y
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    podAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/metrics'
      prometheus.io/port: '8080'
