---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: logging-operator
  namespace: kube-o11y
spec:
  chart:
    spec:
      chart: logging-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kube-logging
      version: "4.7.0"
  interval: 1m0s
  releaseName: logging-operator
  targetNamespace: kube-o11y
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
