---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: kube-o11y
spec:
  chart:
    spec:
      chart: opentelemetry-collector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      version: "0.97.1"
  interval: 1m0s
  releaseName: core
  targetNamespace: kube-o11y
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    mode: deployment
    image:
      repository: otel/opentelemetry-collector-contrib
    command:
      name: otelcol-contrib
