---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-operator
  namespace: kube-o11y
spec:
  chart:
    spec:
      chart: opentelemetry-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      version: "0.62.0"
  interval: 1m0s
  releaseName: otel-operator
  targetNamespace: kube-o11y
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
