---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-node-exporter
  namespace: kube-o11y
spec:
  chart:
    spec:
      chart: prometheus-node-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "4.36.0"
  interval: 1m0s
  releaseName: prometheus-node-exporter
  targetNamespace: kube-o11y
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
