---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: flux-system
spec:
  encryptedData:
    address: AgApjVUQwNLmxrohrAIC0HKqnKTqq9TaiDiLiSsROZxaYU/CJUTXv1ip4Mt+CgKVxSElqzt4rc3ZVUYLf/OkWxCtApiGmQ5hrHT6euB4GM649byFyWzN2Eps+vAT+WMqQzZ7udwfJu4sfFQk4B2K0oTwF8QfzidZiN5Z/V9YbPE3JlkAdeJGhKgf+kE0nlQQzAkQdNWE/P3tDTJF2KIJBkUYxp8sZ7ewcep7s6TzHiymF31WZyYMaHaLatdaL9FmoOjFLrwsJ2SHlbHKVrtPTvxD1kZJ4wIzbls4+Dfja0rvoYPjtB1QdEWBHJSrzdi1wRxLpuKiR8tbpGLMLQIOzQR4VJ7SVZNhBiQ7LeFoUlKN4tQtlOMCLKdouqI42ZwoDdO/VSO/XxrwGijtQju7THOC4V21S3mPZ2q30rQ9Vt27p8Qeq0tr3Hd8i7nsJp84hi7TqsR5cgfoAQl6KVA3cgHcmfbXAVkbGOe0ayJdWZqNNv3RiBF1anS8ig3fEtSxdJK32i2lzVEvVBcDEEx0qKLoQvFDupK5RtlnkqX7GaJ+aqDPz2s/JUNDOZ/HWZd0RXbcFcqC5ONSZVWTs4khuENVkxAb1EztbsgxuFpfDKKZS3UTlHkRsn71fs6cO10pQoeVt5kTpGpfzTcgI7ex/ido2PdnGwMGGlHSYalJPyMBJwCgsXaR2UOwVpkL9uH0yfWMjFjFdD/nkKwiUnOlhK6kb1LRGJDrK3wXdV/SCLaN0Yjss7r8XpMqTFHGGiPrPP1ssG4OzFI8db8UxQgub4B/6/Z43M/aqGEqwj3qErp0N1WL8Oil4SntPfCWSQds6aBbYl18IjtZd47P4tSAouCxST8CJqLcranm
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: flux-system
