apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resources
  namespace: trivy-system
spec:
  interval: 10m0s
  targetNamespace: trivy-system
  sourceRef:
    kind: GitRepository
    name: resources
  path: "./kustomizations/oci-kube/trivy-system"
  prune: true
  timeout: 1m
