apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  chart:
    spec:
      chart: trivy-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aquasecurity
      version: "0.20.6"
  interval: 1m0s
  releaseName: trivy-operator
  targetNamespace: trivy-system
