---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgBhv+6DMVkoVFOUAWWZQX6A7dr4YBmOPzM43hL9S+2q7MgKknnbSYvupbfhbFNtk4GYPW9wmXmHrsBGjp+zMCfZd/LiJiBcL1JPxZYAzJJJ2y3sFXjEMaYJX3cyeolknpK/Xhwe6ExHyhaWtn3SRfusuDBH41PVaufoomQuatJaT1tlKZDwRGZk5yhcwL6gBXrjWivOAbz+W/nqaIX8cVppwcqEwkKSJjWYRtRcL0/Yjpx4sjYBjrKrBtjnr//DEih4TLzzg/W24gA0aBCsBP/bvsskC2wrPS6kOTVGg9DfSskX6oDK9X8S+VNWGKZzvTnD7qhzFZmf4Fo77aQluWlC1HI9fhalHRSPimUFY7MoLhi+xtbdPiwOY23VFIGTrFVEAm7p8OeyBidq/UF0xgOdJkVlkqZgmuq2CECdKF9/OFO2eatVrBunwMqNQnRV/rCt1tBfWTMKKNbsA1IKKg7vg+XnzBrJj0WbG0MXiBWwimAvRKIiA22ZYvUhVS+kRHA/0Df8+6GY04OTBXNMeH27xSBLXRcFjpOSKvVjDpagrJ2Wwb9CLAj55BPNYWebNfgvAVQwoX4ymexkcyAqgbA9pRJ2d5hqnYA/k3Lp00CzBKFbrpb1Kcfodc0k7ez7RhSfq1LDCcoCtwH7voGU5n3GWC0K2iB/SJ31j/QV7dQvznbVqx4yPekqyYdI9WLqF2Frj/qdwRIYmqfDZb+snwHMUEmcgySnbRFe5wdxo0ZDAic2Rc0ivglwmdgyHGildG3hsQ9Y53UGXdftH05lZyDBOatHvCsiqKTA2vxJMmAwNJohmg+9EgEJBUXN4S0JQCTdnB4YS1NWQTexHwyctP1asf7gm6Int+BXgtBDL0a/y7Di8M3PcObBdeR8M7j2vU1ccMzhVRYxFmKxHk44gsakvT0FnyE6n9QJEGs6wc7qUICkKffVnxvKJ44jf4qppTY7dT8s8jlC0xxmllF3fURi37TjiZftwO12s3OGz2SA+bSNNf0U/1FrgRnG3ViPgy9kmPZg/O0MWR90swOMpH4e/v3MXxYDasSoBnaIFpLQ5ANPtPffDTgvwNO98GN1OoOwk6967nkmwDyvHEb72gF7FqA7+CwGT8EP92pvDMLrSlHk/tEvWpmI8cxkcHUKMY+YGVtqvrmM9A3cRr4alG6SEu1IzTQvhyJ5+/0YF37fmt5Jf15fENSUcRvOnqfB/JbPKUpwIRpmxz1LalPOvJFdpJB+2h86Mpssk8OvO81L+SmSR9o/v/yVsKUC3ZlmtEnpnD7tHfX6rzcxGen2JB8jsQV1d+G8VNpmAvSOTNw2e4jG/XRmC4nj9Msk8pBef6Gni37W2Q+ddce1rHBJALdWIwia1oxcEOdvMvdlPW0odsnaEC7t6O2GrYf8cVHZFIxxwu4=
  template:
    metadata:
      creationTimestamp: null
      name: authentik-values
      namespace: authentik
