---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgBa4+nm6xlO/TGBqs79KBPBUUO8e+7OSWeVSSHXqtblqAzKt1OpRERlFXOOPRLRQn/EycnYBx4iEmlQb05y0rMET8AFnQezQVwVgdaY74sAWAQuX2azGMQXR4Vs8N5Wj2MphR+bZ2VnX4e0J0Cqa2osiOfDDvaBVWnRY4OQFx+Jzi/+l4YtQvuEy9xRZKWaJ/b4uoqiXJ4v5C61gmUISqybvbubmQ1TSnnjJSkrwJkftyS3jmvxorGkaPu2Lo5sSIDF6OdsD9fp9jyQT//j9f/XiEl+H+Lihh1t3OBd8ioMHpWaTVlxZumRTvPcPIHchTV7meyMJRcE8NxGwlCqK22AifMJy3Y2fDXlT8NYda9gmUH1VJRqsi6OOWDlPsj32oeHqY7cQKqvtCOBydzd1mLGezR7UCipfjeI2E+in9jENUCVFUy3bk8AwMb1gWjaUQ3Y7nKAK4intHqmAhzZTjcFFJNpQh7JZLuJf6OxQc95B1XYXpBYwvVvyhjnM6f4a7rO7xG8vxA6VVkMs9JrwpKMKnds8uGw7XdCQSdRwlvA+4Q3aUCTedfeWB66sALBUOcfBNbxDDhEnq+XNPhOMTR2IEVgvJMaQZ+neawb5l4lhYDnbGIhPKG192prHAqQS2nQyj/IUqiJJ+FQLB2CiL2foXBGwwkF4lTLaU6VWHhbtl0F29Mvxl/0k85bi1XHyQybUyIBQ97mDuAlVMn5qu+KPLK+97Y91i3vD+bkovsKgyL5WWTchF+DC/QXSw03RPCgTSdX9iA2ep6vph5X8avrdIvFP1LWBjnk8+VBJAULPOTLJam4gf6vZTA8kDwHhIsUkj1nBPkIPqmG43nogs9UpW66URzP0ROnK6JVvK0Na3LlhA+Dd+o+ngkPGcFGSR5oBB121xzU4OYEdvUgqMbim2GxAd3zoPqF1ZnU6DBsTY4ljcZ6aDP2aNrDzXW5zSKbAmXp4wCZtzfgA8euOvDP3Wqj/o2lHipa6lp8fk9LrzP9FphKSSd+hlu9J4itEZonpZyOINTYE0H2VCYxHkI/FpyEZzCgwa/4Oy8MEM9AbLJC0mbtMXA7F+KOXBjFTboN69OT1drDy5eXPbQsfQ4TRayEQTvU1wPZ/kSGhfFgqBvewZm51K7pg3DNWvkfZbVmHbumXEdLiZT/lGCrzy4XDsjme3Ax6lpLuxlNiEmvq3Ed4Rw5OMxLGVpsecPUx/hcA1eug2yEWebc1tN73vTBUJRYxzrjebPRt+ZmRKY1ro1r+w7E6ajdnEs02s3ImLc8C18qm4Bqz4LEsI0cdaiL4vtkpZVF0z/rWmM31TvuEn12BKXSHk9KVbZzco11vgZ8eMkCEHsuurwtBEtd78gjKoUlX5braQmcQtMA16xhNKrua/pfy2+PNI34KCUKjo9mNtOQmF48V0HBdTND6ac=
  template:
    metadata:
      creationTimestamp: null
      name: authentik-values
      namespace: authentik
