---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgBnWldw1juRl2KlUbeAEHEhANY1ZLM9URjEYX6N/FsaBEw+CBsXyL+FYaYCQDqvi/q9Z1SLXMF9Oflw5x55GvPBBx62GJn1CMvhe2w+LNSKyVTb9IzA36+no9kBBN+Jm5PFslidUWsSbsc4uw3mv0QnzAHigJxU5OxRZuYBJ7g/lWwhIP1GM4kCyH2Z+NfBuHEp/8VFC+wiRDhGlDH8OBvutA7cOa5DPl5n3cBe8ZIaOw6PAmCZ5X9OU/ghbBZ00WM/BVwtEKPf4PEngqself7zFp4S9H9rBxDUvcKidWCSx6tJZt10LdjJCehz5aGGXVlq34J3vUfpjEmvYXZuwEmVuSXqPR/f9tpPjxO/kWlbVwM8pZUs+2ueB3SYhyM5tyBOLnO8NV+um52yhmHWMDFXG0DskIL7S81JhGCCCW2Sv+I0RAF8NXgWLhZ5y9xEItttIZ0//4sqLgLAVAnds201YhR8Gg/mqyUH1xP+x5/Sg4JLTHilsWziCwtRcN7YgXuJ9g9ZT8ebMgZA9Ontc1KCkTrIHBa3CyYsdUcdh9i0cHCRmDsAi15geoDCDSwTEhh/jtAvKx9vccGudmFjF4K7/9XqiHGtr5SiwCV3aa5GWb/MBNgZ8/pWI9QnXEiO0b9jirGXLGJIrOpf6qmfH2sHIVUi3Nw1N+rutTZGuKaSQIfEgyC53lJbCErpYj9PIwzXDA1OGjjU23gLY2IyweqjJ7rbHMaaTdRWeYcAUVmDW2W4aSE3I8Zl/X7+yr0Z6R94XLnoCiA1V+I4eeaoJXi/2DJg5SfSu4AV1FPdUP7vKFbQEWxKrW+AIGoIVC9cuuAudb5qeQErka3bEMID2nz4hjuYqywuRyiZloP3WbUOg+BdEl7JMOe3CHqNfAPLtlEvR1/FTnyFte54AMbquhZUou+DFTk4l+B/TmgOX+k2OIIW8WySUsx16+WEPY4bAgyRI1JSgf2JO07Gsc7Uqrf33gLcXHRU7GDe+4UUtl+JB/ZPlAG4aBmWXkH7ixznHNEjfap12+UxPAwuPx6MNzXHL6AukBlFlMnjJgvIZpqGtK63qBqxyx7RlKFBkFU9qjZ1noPzDckYdqOsHqLe+kRhp6Zu3Y6s/AVWsdSFegiM9HAiquwaPysd7PMnCty8m0oxxwYcLKVMlFIlFzbsQZrrrdX6NcefDoJ5m7z+GMtr5hR5WqEXuqREB4W9MvM4NdSchdGaTJ1350PGYohvWbCsrZ9+r2b1tJkzkpxcplsXD8lJWE/Xb1cC1H8wEtSIXeF1hOB+49n2NMdP6Vz2nRQwr9kG7nuciHE94l9kkSC7yh2RyJS913iwUAHCOoH8peTg3xuO+fR4MDRarj7HnCh9HthMPXXwfU8Ia23LiRhpX7SE4+IstlqSHJ1g/zyF9mf2DTtYAkypR+BqbJpRv2UHmiK0FndHPTnLJ15ULsycypPChN9ELw==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-values
      namespace: authentik
