---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgAiRmKm1zerh32a9g2u8gzvQWj/bwivdqeh9hjpbzqWPwRZ2IGtEJNpNv98QVrKy/WFdrmdmgBEWsPKFjvrY7TSRhTFm/qmvDKkZ3CEPnjBJ25LZtDOMy1eE3uPPEt6UFGaNirXlHm5xMgtfWzlPguTIwjtkzwZw9gIxN+d2iJL2yTFty4V8+pZcf9OsWbBOmxzSI7qQcJcSX/0WuZvsREQh35QwCBvQxqTYM9H5s8QrWzOfuxCxnba0SSneXGKZbEekBq1g6nAFQ+H4HQ72NqhKqJJ4GYBGY4DDNfxCONAXwDuGP74j8Zih5dmQ9QbQzxF0qopCCNORMy8lu/xZ0Es+XVYJtso022MwfvqYxf+VB1YKr74YgUezxB6gi0aZWF3DSXqphdDJkSNVtUOndgiD1CEn4fFdjSXeiPVDkeTThWc3Riu8OQtud1esmj5IogzwDWBLTa5Xwgl9FqtBM5AtPC6ufcbRaB5Pq+S12RAFou6R2KOkGFfiveFOa06hp2rv3sQCECWYq75MzGS3G6hZsfbbjTydHcYIOBlI1nfaR53NfpGxg1O3uo3pNuVrgW0mFF2syPTC/noSg673zEcWCwtka6KSAQsXapzHPlQnR1H1sKWycP9oH9RjstTQVAgHQahPhpl2foVTByWnc20GUEnS/PZ5aZWNOxTIOngUCxLNj5NKvm0ToKQZ/iaf3gtIOVBoXbO5yhta3EPLD0JrMamlc8pjZVxxSRpIEfo/R54pLD0pz9joHQpI+nWvBuS4BTI0O5LcMdbuhJVCo7pupN6uMU63Rq3fZ1tkxjKt2uhSCm1RqM60aTtevsrC6ooFw7SsM+B3ItoPHSODB+zGp50KnMA0NbIemqCx1o46/FiVnY7fSpNGvnzemD9YlMJLcXTDSlAjkj+FnBzBLk6Hj24X/AwrTXp6fUlilC1Rsi7G67R8WcR8m0OGURqAXdk6bLbK/paY7zMWLa2Dy1j/MDGC6maEDUrtwmhtk0AMNuhKRMZimiyXvglSFsI1FNPnsY6lcLV3hFBzl69YIxuKzCcqhYT3tdr40wBSWMU6HDyCwBvELUMFkY2Vp9+sktgd3SZRLaOudjmPcSYfTl6Sa7QWydeuYJfqjJdQGKuhrNw2vobZgA+VPbATXuknoAqcuYOzH7Kehu89j8aonOjrY/TBdF7p2quRv1fhE4lCcpJZAmmlP4k+xj7uL4d0g2SZbSiXj7et0wYDuZJvyEnyOIFnPwX5FbKVT7t2yCBXTnhjNCcxaKg2lCks87vd0FSaWH1cSDk2Yl6MH5HRibU+QPfItbA18edugiAOPE7Lq3DRwjohulY6hOsiZfmRZ3pm0QX8d1kTSTN721r
  template:
    metadata:
      creationTimestamp: null
      name: authentik-values
      namespace: authentik
