apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-np
  namespace: observability
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
  ports:
  - name: query
    port: 80
    protocol: TCP
    targetPort: query
    nodePort: 32101
