apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: observability
spec:
  chart:
    spec:
      chart: jaeger
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
      version: "3.0.4"
  interval: 1m0s
  releaseName: jaeger
  targetNamespace: observability
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    provisionDataStore:
      cassandra: false
    storage:
      type: badger
