apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: otel-operator
  namespace: otel-system
spec:
  chart:
    spec:
      chart: opentelemetry-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: otel-operator
      version: "0.55.1"
  interval: 1m0s
  releaseName: otel-operator
  targetNamespace: otel-system
