apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resources
  namespace: tailscale
spec:
  interval: 10m0s
  targetNamespace: tailscale
  sourceRef:
    kind: GitRepository
    name: resources
  path: "./kustomizations/oci-kube/tailscale"
  prune: true
  timeout: 1m
