apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  chart:
    spec:
      chart: opentelemetry-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
      version: "1.61.11"
  interval: 1m0s
  releaseName: tailscale
  targetNamespace: tailscale
  valuesFrom:
  - kind: Secret
    name: tailscale-values
