---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-values
  namespace: tailscale
spec:
  encryptedData:
    values.yaml: AgC1MTD8E+AneWkPRkAlj0T7g/VsCjQ+wu7Z3hMcInBMR4+1cUEX0CFsoJp1lRz0xOowt+SqfCN83fkqVB+vZFhdwTvk6HcxZp7VnPnNuRnIOerF5Ci6mlD2jkfy5N+ze/9K3pvUZPtBkxKBhYSh1nKelxsB6ZzT/4c2vsS9Elke/GAS8+41oeBmkw70rHwvoa5f6HV5F9+Al2gDvleqnKgdPOhBAXWJ69eYzzx7infXkv6sk7SBJu1PgTcqyVhpBLM61BeKH1S4SgVI09q7zEdNVQTgZoctBMCx0td2tuuKJOB0OC2PmSfDRY/skVjxh5KoC0M4fMOtg71XKNudYLuOAXET0d6yAc+98PScjXqmbzRhZoqsg2Hpx5SdGS6kB3bOLWudhHi1q7ziYkgmUq/RAvTtvbWh5SfrZsAUk7DoiVALMOPYPXHn3CJUyGmcLiUjag4vSsshXKZpv4QKAeCD0WqnC6UTQ8BnmuZQ8hvT1ISzwuneibrqWluBFcAYAtXwntJdW6jQmizdPTvBtmiqjJuVdjwNmg9jxB1dftEb7s/ZorEhfa2Feqj2IUCoy0+QPeJd2ox/kpho/hyqDMEhLJeHXTJC76zuXvh50j2EVyc61xz64BpYqcWt4/ZSOzdoU9dT2KUWHCeCjXy0b+m13fGXaJiQILVxiIHiKTndJyO7do+DID7ttRHQ29Xlaz6JO5dKXFgAjmXcNpuRDCX+w8B/vqAiVn5nscT6uim2Z9wF+Cy8qbvJjNIPPm+c2mFwVmnyX3PeBzcXlwuF5f0RIc8nhwERJ9fwXdn9uucc8+lrXvn2sZAQH0NMZb2343zXtnXsWAiX5sAC6j8oTtc=
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-values
      namespace: tailscale
