apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: bitnami-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: "2.16.0"
  interval: 1m0s
  releaseName: sealed-secrets
  targetNamespace: bitnami-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    configuration:
      fullnameOverride: sealed-secrets-controller
