apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rancher-server
  namespace: cattle-system
spec:
  interval: 5m0s
  url: https://releases.rancher.com/server-charts/latest
