apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: cattle-system
spec:
  interval: 10m0s
  targetNamespace: cattle-system
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller
  path: "."
  prune: true
  timeout: 1m
