apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system-upgrade-controller
  namespace: cattle-system
spec:
  interval: 5m0s
  url: https://github.com/rancher/system-upgrade-controller
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: cattle-system
spec:
  interval: 10m0s
  targetNamespace: cattle-system
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller
  path: "."
  prune: true
  timeout: 1m
