apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: ">=1.0.0 <2.0.0"
  interval: 1m0s
  releaseName: cilium
  targetNamespace: kube-system
  values:
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
