apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kured
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubereboot
      version: "5.4.3"
  interval: 1m0s
  releaseName: kured
  targetNamespace: kube-system
  values:
    configuration:
      drainGracePeriod: 15
      drainTimeout: "150s"
      forceReboot: true
      notifyUrl: discord://EtYSu_93t0cPs0uVDqn8kqplr4A5VJGsgyxj3V2He0hmP3f5vUGPkzXcwec4KJAedfXT@1095394381156073603
      rebootSentinelCommand: sh -c "! needs-restarting --reboothint"
