---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBQ0OBGoWBgU3FNXovpuhuU9YEoAEWeDU6sj4P+1xvXpzpjtSCLvdgUNGHdoWcAoYNLj7PmbOCrCQJb3E/2IhEEFqwOHbt0ajPWAlGOCDvEgb8u04Kxgpozh8c9xJKafhdAh/LWxhmrRXNxAE7OVhBjOwA2NVYJSwFfRW9g5+SU1KKX1Z+opG9A3YnW455h8ayDeloJg/fpuviEJfTcgMEOVb2ahFXbeXtYM/pe4q9CVc4KTMc+yaq5hG0ZNeEU1m05KHYsBoqzvF5EmYgAipeolSLQuHjMpz8cjjPRhwF2nKEgZcn2kWLyTgEQXmiOAWCI9MKfArCxtZyUaq/eW16bCapTqjXfrYDN9WxHld9Lyw7iJGMIra0uGVruJpL+Z1CU+sKDrug43/5RiFAVOYOD+ET5hNdO02gpQ7Mvf9Tf3qHBInmuX9mcFx2Xhsurnb2Pwjmkh59vxSAAXk75yfSNXh3W0hd1fxsR4Ky3J7RUAfC188xRfZtr+MB/lTBX1LfRFRjqlkigEgMuJUDy9VJSWHGZm4pubjhVIz51tvpItPuQQeb3zEwbjkok0I0/MoXjRFiRKHvvynXElnFLKzUk7joJgOveRXLhbciDl3oe47kCEDsM1YRc8pJTuCxzHKfXHYTWqfQFo1DPxkqU4c0fcErwHIu9BXdJC3krlSJ7lb5pCiLHK69JFfBALfiN5GIFiXLXwJ7OJyO/0emiXXlLCf1tNAQuJl1NYFcOfc5I5jfOgVX3+uCcdgRwUQ+u+1qOymkdEtY5s4VjOqZ63yxeA8HyFGxihWzWMs11gNSGAcw+7UIWfcAkyDVb8bkH4uWgVDmwmBp7wyfuUp/+5lo+fXWrb99vGkFTXH0svEBJPdyNM5eA5anW9ydPa1jILp+BES7I/AhJ+MOcwXk/veQ3+mJ5LbdgoSu3uRNRDqDkxuHSgZ2VUrpajncNAlH0jemoauTjdbTInSgDKu8UwPs5aujIB0yIYCTYdN7DAw/V+sLZq6wqBGb5bsqsdHrLsesRL2fFMSk3Zgpa6xzRTblrws8X8OC7kq93T6SmwuZyGGvwGuEMOiEN6K3RbJNG3Ce+WWISoLJBzmKUvaOQpfMQUH9WobLOYGi8zg4zXQ==
  template:
    metadata:
      creationTimestamp: null
      name: kured-values
      namespace: kube-system
