---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgA2ChVblFmLogMDBKI7wP0ELasStcqmHcN5OOZY6nAtG75wYgpfu0vABrv6gB+JZGyQgnLKkcEkiegiHHnz5PcX1MX4JP1xIGY+CwdviwMj8aBqoKkFEnoBsgBfWVLVfgCzFlVer3VghVxN1J81raodIydurNFeU20xI6FWiXZmRJfU4RgByFqZZhYeaRUmXhxIaysE0dOL5A2CWSWTqlbs7PaJHvorhvrgN1AT/pdnEIQK6XMgyzY7lHlpER4LhJzZ3dO12/n1CPhtMOzDPvydCTycxppxk0F0DDovfGOvovuOkHxG1e47heN/GKFAlvtY5tJAses510e3wvRG6E+G8yPJmQJxfki65h96Ta5uNyMyY3aDyDXfNzmS2U769tL7Mk157Ry5+/vjG5b+hBiu8ABKV++06IL0DigSZTK5X725l/qiw0C9pJjRnzXfN8p9OoEnVgYLCTUb5fmOVZxJNN6x/uxxJFk2TlYqImVHkaingAEKtLqaCWy78ajuZ7KzQhD+/o2Ozxb+S28GJBQSkzjbWXNVYobuGewM7fjJLpgcgiWGV1ROn+tR8XOtXrgwDjHVFjdrU+Lgvvql2UxtZOpFTWwjkswphQgI2434iVnVXfkGDqvGwFAihjFkajziK5odLM+8vBP4YqZOfasdUrLMFz6PF3DZOTnYArgHaEfibQSCOb8WG/u0F5EnnhvT3N43KCbatnnMweIHBdWuDBAzwjZmPxcfAbWuzI128qV8CiRZA3jnSwWMivG2gUrI5F8GbgfMCl/HAzNBhHsUgO4QOKDVQE3+JZLS2cR+Nzdvb2IbrLi3kKQpKZZNVGkq+WQa2f499w3hMhZm0WbdZboO3qvC94BoVyaaR6KDcWBpBY3Nd0euiFg8GQ3lH/PrK8kNg0iKzzg51Fr/p39K9RYJok6c769VDDX2MoBLdzRYubLCIJKcwvkdovjh0XfWrnojTW7jKmd62Z2clXMo20qyHMFruL7KD76dm8rDqD+KEt4zPlRGzrM9d5zYpUEfMWTjAyAi7rpYM2N/hlKp0AtkGpXEuK5ZhMTJtmb98eUPWwD9+NMGHdi1knMxfFcTNHXI9ttNADIAXBWS51DPuXgDw4mKpqC9UqZUi/w=
  template:
    metadata:
      creationTimestamp: null
      name: kured-values
      namespace: kube-system
