---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBjHeQfOsFT5p2NRmo8CfRSYn9FEjNX2Yb47DSBZOLXsKSDyyzs2/IclzjzV0BgqoeXRTwlOSTbMNlP9rQpBgRB6/SRS6Rc+q5TW9wFMYDU9xI2dVcQvB3fo7zNsK8lZt+kMrFkknCbSQ+sEfjFH4DZE2PCwEFXLS3Gi0ZQYgd5LG1w0ArJYjFfo5HT9Z/sDX1VtfRSpoaVDV+WYRnWOXrg+S3HewG8AWK9c4PrjwGh8BJyZA0i2KJk+hj0tg9oOX7tEepDGcVmpbNu7wNVs6YDMPLfeOwcvrGjN7RWZOWmQ1GddLJUTEIkf1iO+GTBbvPD9iImZzaLJs9gDLgQKMewBcOcy6U1TQeCSlSwbroNuZA329vSXz0KY7Na2+fxDZiirHTd17HIWzN12WTIjt3pRLwXOL7khkmrrTXD3U9fiCkPIjCIb+c22TPkyarcq01wnsBTiwc9r+F5TKoculNreQRQ/R3fXMRAUDG/B1dW0dwmLGQFuWss5kxvfQ68jkD1gZdaE3519uivQpkcd8pf5neWBNlsA09wY5QIQ/xAEQcz6OiEcvsMkkzBaei4xwwUHlFyXq9jvQKWrHVDueC0znJbwVI3h4csjCtpSU8xVBJI2T5Fm9RqvKNCt7OBRLIXiOpDXK5mzqclxgKGGtROPIIpZypQNiURJ7QKwjd3KRX/jFz8G0voELKq4bBmMtPpThpL0gr2BMyTr06GBhR1fQNsOmCMHP7FwPprPKc1ZvFyNylvKSGytlWRqX6KxXRgnZfyEoKDjts/rmG+6Kdq0d/uL3ovU/NqwzwWFaIjTZ4CSJKCQGuyoSjnb0OjgLS9GJUXCiuLy0o0aX9Eyk7YnBYfEOaE3FDfWaM6HDzy/JcWyhDrYn0pUP81EPFpD0M9PdiaVeAP5tro0x8lzeFMT0WUIcx4pGjZsID2MOw76vF0Kaoe0qDAr4ON37c4emkCz6owpkzKsTGEvuf8FbSxLFP0M8tuh6/d+intXoUMNnUdY9JEUqBW+GmU+HJS3f4RbmnFimW1CPsliTjMzkN9tcDy773K9SkIKCix0S2oEPhv+LXCH4+3H3fB
  template:
    metadata:
      creationTimestamp: null
      name: kured-values
      namespace: kube-system
