---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgAKaiLVJtgMcvZ/CKq/85+d2j6DrPgvD5duCFuoLOhtQSyfKxfnxed0BywFEpNFwwMSydTAI6ygPLpWrtzMnXRAi83kL9Et1jQhpDF1OViHm8+6HM1WvW277f0E/c9rZ2s3oNbGE7k+6yvnzj+ggzQR/7oFxMpvvjwmgfD9z++yYBYMYikuRUXA79Gr7bC7AsPzDos4I0KXU1meuCA1jQ1E+8rb2fTQmRfG0j796brAy9hBtgS5R9Qi5thb5Zmp6jjWQzHomVq64sIsCm9lQ155t2oNMdSK0CldRnn6UBpGSScijfAEbUCV0FWkz2iSvCOVADQqiQS5ExpRhC7UDoL+g3YNF2lRr4Sc2ooEiz/MxHcB7yanL+2VlCpxcQyY/jD28R5stXwlIaRRetD+HgUQ3KVU6YiA/QhmRunurmqFhkLx2NjOpvqIqvKDYG1a/9JH6LoSsxXHDL0XhCrsAjqPD8heOVVFVbBWWwz5geZqWfP8PRh7XT4ggemWJHFc0qgCDQYpkpFeSnzhuh3iK5sbf83few7P6pLoOV/QLz6WZ/AmD7Gz2h0I/3hzEMzCkEeWtrqHWVqX6V1yvbSkHp54CAVAV/RgD7P+WEW7AN1lYgmx1YTw/jBgfY/g+mtEHpjNKh5AGwxb1LSiWLJS7+3gJy1DzBPNaDD0pFgsokEnVDWB15CkqHg7jprdhesVnk+IR4B0wU07Kt31HiRliSlqhVsUHMoa5LNahhiIsiljnfTqv4juGZkpSSjrl2F4DsPF3AWEUjE2rG64UBjeQbz9G9KV+aKFaBM93AJJhgpPfgzO69MPZPrbHp/Endqpd1rshGWa7VGj79MCXWD7zn6+6rNOHrfngkAGvwP25VmHd0d8jFiQDMg8eK7JqFxwNyND8BPLu2uybi88nJBuNvgmdF+xgfVFHReBgJgmjWHXD2TVRcVMWOWvqIwDBQN9wqtdf/FkkW38+JgkGaRwZ2pMalZI6UQ6bKyBLm1XvrI7W7p4pZjLwC1nNW+XMuTwqQTCN4qOVabVoYpQzPOlrSnlralc5IxPXgWAli+mjc9vK6tOq5Q7g0clAnXIq+E2Q2EPJXlC/S3+TOCei01xWoVnmWZVqsIPppcuf09Mxj4DMeii8saT+sd48p90cB3kHCrfu+td4bpDWriWH3o/G4ZhIl7x9RwLO5FVdpU5wvJ2WkhxtY1JxqQuS7DRUPHZAIdOfvYFbcAEW6PjKx59CcnMmjDweS5R4JvapU4dMko1EXXieBeouAb17LU=
  template:
    metadata:
      creationTimestamp: null
      name: kured-values
      namespace: kube-system
