---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgCJrFOdKSxA+/2oVlH27X6CrqwzisGMuUodXzds1lUv/PIjVVNtD6IaD8CacrN1BoAF12sYyDXgpq+GKrNbSR4U5TTDj2dNL3nslvKVrQHc8KET3HFeJ9N91jZvm+zGEP0qUoebw+BTFo0+6uNn0nP0sLtyphokzWEQjCK2XW4Xrj8QUMyHB8cpgJO03eaBckUODRtHh5p5jJfUnquJihvRX/4t82R22yweq7zlzgTRbm/Qa9Bp0Kxl97HwwzvexsORiAb7L6LM16j1klqYgGyexXru8xKF3vZYM75ZUx12au7gLcusV6pdyULXQ1LgmYnXQuK94dT27R9T8rOz94Flj4qV/zq/0NYiu2cwbAT8/1I2zxSIMTdfQIiTB216sov+2r5Dl5HNrzraM4lPDieZ9Zsd/3qV3gICemGEDYSj5xKmsxoryx8t+0n3uJvRlYXhzEfjVG50p5wfNzaUohl8qAFIuQgoctjagP5lhKJ66rOoiFlKhJQizqH52XrhbxaTwiPME3IDhSu6jciS85p07YM8Aw+n99srlZav7Q8vaveTehZarJGLW1sDRPz/OwEsksKTo0sySO6s6WIcTTnNnEWU9vXKNIGi+39lcFmYtfRYS+Lcg0P0Divz8+TeRNkfPVtB3V+sxTKYBorlCkXt3umh35u2uaZGB2PEnRTSIHJFZRSw2A2/bk6ZS2ouZc4MevWB5JF3C5bkR9bqP9mq1GC8GQ1iRkPZwsgcx49zW+LmpYzVIkH1nUWnRcS3JK+eRGqyeKp/dg9ba5AGm+2HfQBIqsoa5fImDr99tvgYavNXs3upfFwsT+OGmEEaZTPx5s76zTk/D0zugvUnqkUXWlUPHZrsify4Z5xG9k19ag/baQgia4FDqOYclHSplF+899pd1WGFS3ompdfI0/SsIg86kfjw9POuO2mSvxFvrZYGu/I7cZ7hBHig583u2/gZ1Ue2+ITUwY9b0CjueV4Cdq7AZ0Wb+TJ8bDor5uyPe5Ei2mZZC9t9jgDcmnFhtK0jciQlJYAMBFsE1fTDNthiTgutYh4LmIaYqzQr0d3dK+Jh7GQyreFzeTKhdETCttSAT88cRitvQz42QvExaG5isFPXU9HLORAc2U+EBaqiSjrgohdOLwqYUPd9beQpONsSEfZu
  template:
    metadata:
      creationTimestamp: null
      name: kured-values
      namespace: kube-system
