---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgA0QvZvcg4D7MxgZhwUni6ReqKeVqE9lfuLRlw9/2uBtFIQ3TqiadYWi7OPVAyOmPh1hSWfwJfFw8bsvnlcCjkqALlxv3ddlEIK+YZtmQPIvODsttmX/bCCjE8dK11VY4FoI/JR1IhdzpHC4hY29lO7uj9qDqgJT58x6XN8Q37qlf/2z43GGTLZ5OlglV5Zs/6OoChU+HrijZu5FkfjKVyJH6u2gKIqbRxk5mqRmCk9FmFf14uiYU/TVGfo80JY8tiGfiRONZkP5J2ntOliEJ+YqhyhjszK1PQXHvLrhoMdZhEyrTEUQOVCj8pUtVElKwu094MwoueF8WSqGCTjEWhlrKpqEav8XGN72jLDBme58mPLYmVsSWqGyBewml/uyz1h3Qs/XaZVxtyi+iu4Wf/Pc9gOCdXC9gogifvo0m65yQQSM+NOFuDeLUWuUh3dXON4wD6pvnNzfZ2RgDUtSbsjQBoELbE4PGxKxBIYeizBP6kLj65HDSaTe6Sh4WbnMAO85jMLG1/wAKctR2bNqPUOtsLkKrwS2BdLSDk4eoP9rgj7fEQ3nxNHTV72/rJ5ZxqFN6wL1F6JaPuRJJ0MNuc8vSmRA7bCbRHMVYnQ9mE2veDm5FeWVNIo+okmMFALF9qCqrw/lDzMbxz1Gj5Cic/N35MnBvnygLPyc7a/mnup70+kNML5yeaadKX6jXk+dUIdZj9BQR4PWmYIKjujR7Re36PPWd7ZASZceHrRUTiuwe5Mkvm1XpyZLEqkEwNp8Wdk2pZBw7zXdi3OtgL1aZ4PIKe8lcPB/yghb0BlkVtuZ1mHDukTWwX5VT30JQhNgl7StWYNErqtBP4O9yvn0ctrmL0r9etAjLGK7DuIISL+7MFHVEZxZkis309QyRCFWE6kgQ7xI9DLj+h14C+E90kkqJv7ga+bEVOLTVNyqYtAKH6ax3dDMKd4mt3Nwu660RvC4PzEzWngEdPYlS2F9DOFKDg7Vrs/s5hccoPD9WfiyloWJSoPd2PnR8WsZw5nfIHVcBoxb08MjfWqi1Wr70LghVfPwme1tIPWyWJuMDkJpAAsKR9lxpehDkTt
  template:
    metadata:
      creationTimestamp: null
      name: kured-values
      namespace: kube-system
