---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgBexuKI4Sga8vXNdndoc2e3eJRiTPluJgCRYvhW2rNCBnXD5GEatXgtSzwXM/nzT3Nv1oY1Y1PZK8QrlbzOTwZ5NsjuR8K6R6emYBAusUNIrjR12/vI27lcCKJACjlN9fLm7+5AjFClGr+e9U15oOA74EeRwAN5ifkJD4vHRXI2wdYfkkQwTP6RtLahztJLKnphl1WwUA3VcqnIJ3sEGDIVcReJ07SUDe5PiSq+3lfBMrL5G59EcygvZekEU+ia2+UbZ7Ia4AWWE/5O/L+yVnrRdhdK0SH9eDzz2sd1CNu2m8rakOp6pO3d+HOJ8kb+ImTTQLUezv+sPTSd/xBsinm0qgrLVpNu1OMUBHqK1JRYSXHp+3RUgxL0F++LoBthXBoLVeX8qTYMcHmIU9xKUx0qq5CNX68+iVgQGgzCF/u0ZHPH/2gh5PaaFbVQWi7AWT+aio0HaTUsRxXR1kDZgzjC6OzhV4sjOWLtzMTtZkhpcjV9awzcoLzzGnneNKD+I3cKKcgjYOPzFcOZfxkRklwvlRvE7S+tXinAGAHwEYUsBluUiQASs+n47PHxt92J7Xjn78XyhsZtFZHIxIEVz8pSDXX0VfvbFeaFqrenty4hiHmz1tD6SDa2GuDW9LBZ98NTVAe3pG+fs4Jl1D4x6XiRxq+5TZcs8YUKPMRY6Mowp5+bRp3nWo9Gi15MKts3yoIfXPgIhOyMsauSd9x4jRIOEipUmqyuyW13jxqTwHpSLQySGcoLmCF0xFnvXKWGscIoaBa9YHaMVFwMJN1PmNoTTDISyyd2NaU6/etOrVkxhhndcIqbpuq6KcnujW4Gn4EIIci95Ai+NSpiKpu0bgneb+TAjZTGjWn4hhRvrEOlBoItvYsQhCQ4mAJOPj5VoCy98+R+8sZnSWZLltxkr8yDQOT6I5DeZLdisALQkvDrW7a31YT8vnUvJ8O/e0csZGkyyXYXJ0MM0r3epu9DXQJGsYXsA/k7FbZYsTZfR+TAg4Am0JCL0aYVCoO4QwrT/4APSIeRk2VUUE3xc3wH0NNbn6Qbwis6HAKGMIeWajfo0fMzlh7VQSVj5ITp
  template:
    metadata:
      creationTimestamp: null
      name: authentik-values
      namespace: authentik
