---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgATKmGupOwdoa4i4YUR+OxWe2/4ZHRM68y+4lRMzgHe8XsrJMk+uW0QvbgqcAxpPrf14N3okgapSAgyomYmws35UnY+9PccsgbvH2vuYg7EdRZOLU3Ia0CzWxWSVOH/Bmi5HLt1YoPt68PpNOtNne94gJkPewwMXyrfIbOuGVLiTeUj2Xtj2QNab0VEeL4RLLmGeVb9YkA18JZHz6eesF9Jr0EXGWIK9R1viH+dsgMsuE+C7ThVMCfqeJ8UgDMCx/IbRpuuFM8Lm4+TdTDI/q6Snr4iWKImszpFk57fFNsPN1IDMCNq/MYu01twDRVkiEklpPNciUuT45JRKk302Kh5oe7ClBl69rHfHVWG3TjlGyxrqH+85C/u0PDz3Ase5YaOwgYB2N4fGDrBmKBrYSgblg5gjVWcaHPgWqOuCiPcYBSx041jNBgAmdNEvYcU1itNMOPe5WRb+70X822/WF8h3j+rtnhD2xZpAdFlSWWd4viWcUVM8xVvsMDYm8G7nUKQZWpMPvRCdZuTmoEBpPXGDbYkgQqZwrCnJXHl4euWNQFvAJunC2hEt2sAnDcK9OWHvzodjZgD8+tO7vhLwylHdF8WSM0cLvSfW+WJpiT7UrwTjvVFn9+k/oi9zISYWMXeMQ8roWHPtrkTmHefqOjm8LvOYip4j4M+j89m3A4CYrQy3fZP0BKdLpIEjcSxoNSpM5Rzj9kyp2QgtzVnXMvXzSdzQ45jrZ21+JzZMuP2bfFxuWN7eDbQrPasaVirzTpl5UxEDaFRDYi1dlFp7lPCTEvW86ONiaRpTm3ffvIJM9ChzkN3UOZg1LJqB3ZLFxf8IkGYE9/yabJS5r9HHQEb+pKBHTG4KjL2glRtpQBg116oXsxREGs3IghDY5ZMz2liuYzzZgOn+A3GvaVOobJ7wJmXOVc/xwsY3XjhhMc7+M86oVblQebJ+zAbW3ESvUbn6XaaeWrVfzn7bhHjfw579c/sjtPw5yfMhEppiau/G+7chXYw6ZXnJWKT+QBwuti2DRH6e+vW1Oa0VZ2Ui7w2SiZ/IsxuvZPDFZ5FCyfXej72d+rz227LL38Pqk8=
  template:
    metadata:
      creationTimestamp: null
      name: kured-values
      namespace: kube-system
