apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
  chart:
    spec:
      chart: tetragon
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: "1.0.2"
  interval: 1m0s
  releaseName: tetragon
  targetNamespace: kube-system
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: tetragon-pod-monitor
  namespace: kube-system
  labels:
    prometheus-operator.dev/kube-prometheus-stack: scrape
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: tetragon
  podMetricsEndpoints:
  - targetPort: 2112
    path: '/metrics'
  namespaceSelector:
    matchNames:
    - kube-system
