apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton
  namespace: kube-ci
spec:
  chart:
    spec:
      chart: tekton-pipeline
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tekton
      version: "1.0.2"
  interval: 1m0s
  releaseName: tekton
  targetNamespace: kube-ci
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
