---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    address: AgA+Gjx01SOSmF2Or4mqxvhtRc/Ux2FaFXBEqgSRKlJHxzocrA7r0REOdDSujNKM/fVZXPHST2xnjKihFc20P5z6CuvsWTJk3g+4FhH2xyP2TAVsPy/Ysq3MSJbQXHFayX5bYnjUrKEiVwAIGS00bpYBWKeQjeBoW8Chj4yovXWR8NmSiDkf5dq+3LS0T/1/yO18UcFQbsZ+dcs0Q+Q1L2w0uiSMS8R3+MU4IIo04Il4sh1jRydPYFFEcW98B3WNaTcD6qF6U1yk7F5UWvwVhhH4WhOELXcgL6VqXmJPtmD5fTlC6DV0Q2kg1Waa862o+jm1j+DjDMhEingvy9LznKIwUbXkBA3emkZ16ezMgz4MuCJy1D2jnAiezoUNna/okPF1L9Ahqi9hE3NL+YuyEqgiyz/vaI5CupOY9k6VYuAa0/g28KfxNWy4Hrf/gCvpa6BPrXotuk0w+wMEW7/tH0moW3rpR4sfhrNXAFXejcAHDLz4Tj+Uo9Qz9sYtOm31b7MGZuY427STHf7YGiAl7TwB3LigZTbXlswjixzN/Wuixenk9XqKpPsf814TzIGwPE1R6NpaE4p4ZYfOFEhK8xZ0tmT5jEE/U4AxXgtHgdVAZa8uT2C9xDXECX7C+SU8olI0waIxMv7hNCbAt/lnP0nWtCinN5btsid+xfFbhfANJXQzEv1Zou64HA5iVrisVvJdOBzKJAojWiB6GvElQ1qoPEONiKRuXI0naB7eOIDdcAYZoBOsdIx1zopkpMWPrkT4I0wxqm5s267k0oPfkYOMEHY2QfbbX6xaHYg6Hck8qrGvFGvSwcKjD/FCy+I5M1NtZf7CXbZVIiUcPJDZvhzBlKWBxXLAlqeY
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: kube-prometheus-stack
