apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "59.1.0"
  interval: 1m0s
  releaseName: kube-prometheus-stack
  targetNamespace: kube-prometheus-stack
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      admin:
        existingSecret: kube-prometheus-stack-grafana
        userKey: "GRAFANA_USER"
        passwordKey: "GRAFANA_PASS"
    prometheus:
      prometheusSpec:
        enableRemoteWriteReceiver: true
