apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "56.21.2"
  interval: 1m0s
  releaseName: kube-prometheus-stack
  targetNamespace: kube-prometheus-stack
  values:
    grafana:
      admin:
        existingSecret: kube-prometheus-stack-grafana
        userKey: "GRAFANA_USER"
        passwordKey: "GRAFANA_PASS"
      ingress:
        ingressClassName: haproxy
        enabled: true
        hosts:
        - oci-kube.tail4d421.ts.net
        path: /grafana
    prometheus:
      prometheusSpec:
        enableRemoteWriteReceiver: true
