apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resources
  namespace: kube-prometheus-stack
spec:
  interval: 10m0s
  targetNamespace: kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./kustomizations/oci-kube/kube-prometheus-stack"
  prune: true
  timeout: 1m
