apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: jetstack-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: "v1.13.2"
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: jetstack-system
  values:
    installCRDs: true
