apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resources
  namespace: authentik
spec:
  interval: 10m0s
  targetNamespace: authentik
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./kustomizations/oci-kube/authentik"
  prune: true
  timeout: 1m
