---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: kube-system
spec:
  encryptedData:
    address: AgAmGg9NGbug+QsyQAPlzki5UKdM+QZwh+hkmcJIB6z49I0BMAhttYTluWGayEKcQHG7dNdpjqQSPhxAkH2PYIO0hPYvYPyMp2aGGUinlmqWJMFkiNsQT0VkyXwlbBLSQxbZgEkJoqmJuP1p9pRgTf5H6kkfAcYhUz41GQwmPCq9/autBiDAFnnpAZrs2VF3ibEjNJ+P02tgL3Q4/dkE1g7d1PKnbRcKcewQ78BtvgRfb+cWkm//rFDxgoIr+2IQt9wpY7Cv3msP86JCWaweFVDXUy0TLx17r34oNFTSnCXpTFjtPu8CyPgMUyOxWrCYkTO9cIpKAObOlZkJh874WoAc6bYa8GDQRw8raPq0nnq8vj0k18POOWekaMGHwKNAKsvmpkIfAUJyFhmVFbFPKgYh0EwXhJlHVzdOuGh0qbHC4IeMWhkDhQi+DKmMHfjkZECqVqNeZ2oo7vrpaEhxQ9EXzrXPJfvNHy2NjAZcqsH78on7B3YY1Nd6EB+nJzCqYQg8qt7+luXWQYXsIEMKRyKlNMC4l+biwDVgJiy8rR2M3owLIS9uNQtjKyuZcfgGRpU2thiQMQCt0ccctmNidM3A1R809pbQrEuKcmq1LRObGWt4OXq1R8BBYceP2tKxZ76UjxZNm9XYl1girwHLJo+BC5xQeWTgh9eCmHrfo0bLurdRTh05SwS1cihn6tw9YFF1rqRCYCUEvV63vgYLqTMCLM6mvfTY125ZBspXt7I3GeJ6vc8y/Vd4hy+XgQIfYgVP1H0myF+THnr4MOSVDV8bxtb426rODr27t13/S362OQebNGy2Q3y4wJdfFmAME+K8dQ5nvGkP/gCLvEbyWuTBeB9lA4G68OEg
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: kube-system
