apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: operator
  namespace: minio-operator
spec:
  chart:
    spec:
      chart: operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio-operator
      version: "5.0.10"
  interval: 1m0s
  releaseName: minio-operator
  targetNamespace: minio-operator
