apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alerts
  labels:
    alertmanagerConfig: alerts
spec:
  route:
    groupBy: ['alertname', 'job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'discord'
  receivers:
  - name: 'discord'
    discordConfigs:
    - apiURL:
        name: discord-webhook
        key: address
