apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: kube-prometheus-stack
  labels:
    dashboards: "grafana"
spec:
  external:
    url: http://kube-prometheus-stack-grafana.kube-prometheus-stack:80
    adminPassword:
      name: kube-prometheus-stack-grafana
      key: GRAFANA_PASS
    adminUser:
      name: kube-prometheus-stack-grafana
      key: GRAFANA_USER
