---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kube-prometheus-stack-grafana
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    GRAFANA_PASS: AgB82APsGkRf+fXFNGtqieCdTMaZkrrzsWEk6d20S7Xzhi3qdWvtXRZPNUshsHzvDXDNCH+AJTbmhvd9XaRm8EoYx7cV/y7gR5SE/55guk7dmKM2/3R6GrWSK88AgGyQsNQTiguhS8RkE8V/VOf5sOcSQXgMWLx7sk7JQKVADw1z+gNhPBCXRNVALNwK0fSko2qNB2J6R9LK/0fHNJP4eJFhBba6p6EuxzYjuJWdxW5hUJwNsEbezn+fVcv26FyQCgvnxaXlYdEuapHzPTb/fIu3JIsmu2zxT3PbOH0blA7a5d2ed9aZdd/EATya5n1NjtWDnIk2C4QNv6pTaglFEz0n6MTAo0kofhWItpTt4JjBpk8PUaiig64jW3SlvRAGRo+m3Fyc9jPHtAsCFUcR+72FbiOvhzBHP8MONCJthMV7lyNt3proZdgcU5TXHZLdrN8PgBYUdFKmYTIuRberqOXpOoH7aeSMU/iMlb6gXRuxEu4GqH3qblK03xnC9n4YbOuO2WKE9So2xf+BXrtHj2Gb3nB2P8qWiY30nMPM559TU4c1bLel/SNwzmNcKueIOvWR66+48YDr/J3yLTjFidg5FN58UUMRc6PDNpFM+f0xA0JIY8AhEJ0B86JXRpo2HnzW3TBWTIuwjdnfCcgWzUPoaIrA1erz8CEcuS8R5le4uowTubZ99KBZM2FhFn3CTO9m8Jllrfx34GBM
    GRAFANA_USER: AgBdtJceVVcfdDeE7iAjKWka0M1HlFt4+OavaM94Y+MMSxTK6CoRsCqI5dg+MV5iAuFV8mDaOvOXICrvbwskdz0jCkggMANDkPSfUaHaX3T2QayGqDVy8L1If05qAKxp9x+dqb7WK5zVH9l7NOwlhfoAZCNn7Vw2nGFdpNo8JxoMHbqhFcBWn+su1sQh5U2kN/SP9Xbi9ynzDLFEBCfgihMx4Fx5GtZPjsIY++SJaYA4hQkMPoD9Tpz/2JOoWbI5PnGVXlXE6Pq8iOpSqD4uy4+tmmoadJMrZ9/B+pNIgzuek2RLoASqi9ftU3IpIKPCTnQFvEXRs9sLPOBMZrpqIi+xWa13MMBpkJIN+3D7LXQH6NZHSPr0Se8HmvsvUdOYsibv5yLDQFEMZxBWT2/HVDRXWTdd3Q4lZ4nzb9RQ6sb/qS9FqNJVi7T50IZP847TGraODad2eTPqIHcq6Oa3tXhBtCV07F+E/7YTBKu0KCULqYJnmSgeOzIt9GiLfAWCII0japLtozNEJlNcrLZinFu3Qf7LF8XyIjLsy/GIGlwwktE+3+zk+c8q0ERdTm4arroYr6pnKzBc5yizcXEspMRzqGqgS7GYQpCdGUskoQR3y+WHRkstFsVRMCc8UZClpI3MwZYL47HEN7Qi5i+8T09gPESdfwqXEf0r6wUkRstzOxUPHPMM8Q0MUMKB3Qcr0urLmdmF+g==
  template:
    metadata:
      creationTimestamp: null
      name: kube-prometheus-stack-grafana
      namespace: kube-prometheus-stack
