apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: monitoring
spec:
  interval: 10m0s
  targetNamespace: grafana-operator
  sourceRef:
    kind: OCIRepository
    name: grafana-operator
  path: ./overlays/namespace_scoped
  prune: true
  timeout: 1m
