apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-operator
  namespace: monitoring
spec:
  interval: 5m0s
  url: oci://ghcr.io/grafana-operator/helm-charts/grafana-operator
