apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  interval: 10m0s
  targetNamespace: monitoring
  sourceRef:
    kind: GitRepository
    name: prometheus-operator
  path: '.'
  prune: true
  timeout: 1m
