apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  interval: 5m0s
  url: https://github.com/prometheus-operator/prometheus-operator.git
  ref:
    tag: v0.68.0
