apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: "1.15.4"
  interval: 1m0s
  timeout: 15m
  releaseName: cilium
  targetNamespace: kube-system
  values:
    operator:
      replicas: 1
    nodePort:
      enabled: true
    # ingressController:
    #   enabled: true
    #   loadbalancerMode: dedicated
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
