apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kured
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubereboot
      version: "5.4.5"
  interval: 1m0s
  releaseName: kured
  targetNamespace: kube-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: kured-values
