---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBu23Hjxm1WGWaPyextDTbeZ0RGKHFA1nwSUQaTKBsdXIQuISaMPEbBC/VhceEVaaBQFyGj7f/nq2sc+GT/iZdWOSWcKHS7XMaKX9pfUWzhbI4AEjFpP2u2Jt4lMV+vS1WbjMCcDtnTYNYOqw+t3iXmNqmrd0k1sAAVRx14F3PCaS1XaHgCwfjJ6w016QGuigcYfvgsOcmKdJ7+Cm2mAysOe3kmUKCU9d7R1y3x8kRUMNzkpvdQQlCQiV1yCPuxQ73iZ3HdpiXnkJpIy4ln798HOUOCxzZTHf7R5nGn9mrTVO2BMx/3T7hica/N1BjEe0iu+o6SRTlWlIh/cE6i+gEJaMBpdant2yVSqt59jIqZd4RDOHTU3ZtcnvKfh4mHMVYjNGeEzSIfWQlLjcccHI6Z8XnRTCdDFBxlNNL69eZ32UJ+sO5hdcIu9142fGoEy9XAMgSvfg+EEMqcOH6ls88Z35sunvuO4UcpmETzvlVCgEKN7IUcnJhrcQsrFJYk7xm/e9Nd+nDcipjIhndkhb0SQWg99YeL8bxUVmJZfDMLF2rj/KZl2hhW8uiFfhiMtSw8lBw3IcIJ+LX022L6P0CLSGgPzf1iXGc6Cz7QnWKKL29u9O4xvu03iNZLoQQxNMd6fv3hXZUw7ikgY4Rnki8FSortHmwIKa/j3sxcmwhmXvm9RkKAWDSA7vymLYnJ1w4UaMsEaxcM7dEL7/iouLTir/nMU/iG7TkVJcnshyFD7TfRd45Wibt1PF+MsiTih7PIBdkCLwRz3raQJw+FlfcwsDpfs3UYQqb+lmp5zAu4NBz0Y1cjHb3qKdefDfzSHFFsLLSMpHhjvg2yDp0e/MxpVHUs4HSQTu0h8P4reDHC2a8ZUo9EYWMU0Y5p+PJbkGOJ4wTRyuS4BQ3NuLIKcHmAD3niBD082Rmxjg8rFSVwFRj520COXg3wqXDEJVqFSGNmkIkTI8NTgcZ6ATqKe75TFWGp+a61KWdX
  template:
    metadata:
      creationTimestamp: null
      name: kured-values
      namespace: kube-system
