apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resources
  namespace: kube-system
spec:
  interval: 10m0s
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: resources
  path: "./kustomizations/pve-0/kube-system"
  prune: false
  timeout: 1m
