apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resources
  namespace: kube-system
spec:
  interval: 10m0s
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./kustomizations/pve-0/kube-system"
  prune: true
  timeout: 1m
