apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
  chart:
    spec:
      chart: tetragon
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: "1.1.2"
  interval: 1m0s
  releaseName: tetragon
  targetNamespace: kube-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
