---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-values
  namespace: tailscale
spec:
  encryptedData:
    values.yaml: AgBLXOTgV80RnJ7kz69nKFkCQU+xMaIaN0v+iguBJ1bEkp0wOiZERr/R6LyytkhYxfjDV1u0wFwrNeEGPIP8Mddw41SkQxdiYgCbgXNrbsgnBk4Jwom1I0MrkdfCgml99EPkSfbn05Ih18sE32bz+r/d1R9TT14WFkhYSLBfcGUG+TUIhrsgeIMfV/BWT56lFXYI1yEri1BOVg7TkuU9xZnYkx7hP6ZI/vLynqocXofR3BfjKO3JNolmvoCT71S6f1WJxiAnIzp7ne+SQeKGeGTMBlZ97jDI3lcHxI5t01I1FxLKJRJeN7OxKA/wpYVgwv6rYLPLNo5k1KNOjHzTF10WWQFIUMTnp+u1GJarzuVrhfcRDDMfIsUmjwyOw3D0GKNgXS4MBtcBfoGRDp4HlsCzONTn9x95gv4EKGl6RBVKd2T3YobcZvgXx8MKtM0/+T424bAWDCfM/UnsXtNcvC87l10Z412FFHzZ2Rl8Q99DjNgzKwpWm/UjDHeFUSQGp6N9WRXCchFXOILyzJd11GUXO79uxhjkDVLNGGBNHk9RiufrhdqZQaSTDnTViVAoLwmAuvZHBFhJjXo0TEsWW9sYcs2WNhNrM9qMqQR9fpICfNb+aBdEMgkdm30x/eNhsuoId9rqBS0J+aDMxG1p4qYAfzxpAcPjl35YjT9oH3xoSXALg06oXYgpLT/so7t7zOyIi53dj4J2Y5/R5YoDaeGHS4GB/C5JBC1R2lQDpbqJbxeRp4mmfWmsWuw9O6IoF/tQ875HkoxDsdiy2N7lS3GGxVXZLuN/YCZCHFGicWuRYK5wZOSVNxA9BYjNQ0x2BrAiPYENq8V4xDgpaMDJqNE=
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-values
      namespace: tailscale
