apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adminer
  namespace: cnpg-system
spec:
  chart:
    spec:
      chart: adminer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cetic
      version: "0.2.1"
  interval: 1m0s
  releaseName: adminer
  targetNamespace: cnpg-system
  values:
    service:
      type: ClusterIP
