apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator
  namespace: prometheus
spec:
  interval: 10m0s
  targetNamespace: prometheus
  sourceRef:
    kind: GitRepository
    name: prometheus-operator
  path: "."
  prune: true
  timeout: 1m
