apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resources
  namespace: prometheus
spec:
  interval: 10m0s
  targetNamespace: prometheus
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./kustomizations/pve-0/prometheus"
  prune: true
  timeout: 1m
