apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: haproxy
spec:
  chart:
    spec:
      chart: haproxy-ingress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
      version: "1.4.1"
  interval: 1m0s
  releaseName: haproxy-ingress
  targetNamespace: haproxy
  values:
    controller:
      hostNetwork: true
      ingressClassResource:
        enabled: true
