---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: kube-system
spec:
  encryptedData:
    address: AgAzc/TMmCnCVV79aMSoGrad6/PSMQgBUXikVBt4Ljh522v8To3Sqn0zi1J3p5MRa8cH/58dqVMpmtbx1My+kB9MXl7wGp8VUEuUAawzi/lhXUC9N0LzKPBvUW+/i89IGUvZET2Yci7pvmfsa5sKOFzqC3F7ohtLh5YdX4yOZYhNSQD8eMgOT3D2tmnDtJqmLrLGKN6ljxmehDY3Ygtv4+kao2m1CKiJcG/v9gZC4QFmVNRA4sPfd9E/QCS0MzqfyuergawgPbTfqpSh2gQxZJHIbXn7wkGBfxG0v0pvrSt9+PhCfuYGFtlAUVTjXCC2TAsQnrzHZOH2jPBnuJqnhipB0V73HRI6zwqYFyDX0H60I03SNsnz6rm8Mujfwx3H0QY5wkMhB1JGrI7BsDHFPXlfupEEBIlBGMrJr3eNOqGpEXndbzJXo12O9ElEhfN7AS2HyGgN0FpQ/s4CqJ3UNdENd9dZt1HfKuHtpixnXipWYAAIo/OqxTgb5Ri5t0tXKWaay1kNuG66ISapDgBfHZo8Ga1QM07qjqqR/pIQj7d42fKbVU2PMiCLSsMSHPVD8wqwsYipokzidycolYXVIbN6/ozGpMO+EGWejTxBStSPRi259nm+VR8IXAH43eM4Ducx8CDyXkiDa9cSa90Rq7YfV6FyV+R9X2T4iv+YfqjLSKuUsn52FW7qMDpqMWTMcAxt7UKLHILNM8ZfnKo5S1HipK/zxuYs6TW1gr3RvqDEX9A7Ntq/9NDAYV7RUm7cr9TslX7MoAbd8nn8W4c4avu6l8Rj68t9WPoqZr8FJdG4kn59k+JbDI4P6VT+LKWgYiL2GB63GDXGMJN3uTHEtlb59dD+xT3BsKuU
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: kube-system
