apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: parca
  namespace: parca-system
spec:
  chart:
    spec:
      chart: parca
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: parca-dev
      version: "4.19.0"
  interval: 1m0s
  releaseName: parca
  targetNamespace: parca-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
