apiVersion: v1
kind: Service
metadata:
  name: parca-server-np
  namespace: parca-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: parca-server
    app.kubernetes.io/name: parca
  ports:
  - name: http
    port: 7070
    protocol: TCP
    targetPort: 7070
    nodePort: 32102
