apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: grafana-operator
  namespace: grafana
spec:
  interval: 5m0s
  url: oci://ghcr.io/grafana-operator/kustomize/grafana-operator
  ref:
    tag: v5.5.2
