apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana-agent-operator
  namespace: grafana
spec:
  chart:
    spec:
      chart: grafana-agent-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "0.3.19"
  interval: 1m0s
  releaseName: grafana-agent-operator
  targetNamespace: grafana
