apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: grafana
spec:
  chart:
    spec:
      chart: loki-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "2.10.2"
  interval: 1m0s
  releaseName: loki-stack
  targetNamespace: grafana
  values:
    grafana:
      enabled: true
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
    singleBinary:
      replicas: 1
