apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: parca
  namespace: grafana
spec:
  chart:
    spec:
      chart: parca
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: parca-dev
      version: "4.19.0"
  interval: 1m0s
  releaseName: parca
  targetNamespace: grafana
