name: Basic Linters

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  shell-linter:
    name: Run Shellcheck, Checkmake and Perl Critic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
